[package]
name = "full_history_avd"
version = "0.1.0"
authors = ["Nirvan Tyagi <nirvan.tyagi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zexe_cp = {git = "https://github.com/nirvantyagi/zexe/", package = "crypto-primitives"}
algebra = {git = "https://github.com/nirvantyagi/zexe/", package = "algebra", features = [ "ed_on_bls12_381" ] }
groth16 = {git = "https://github.com/nirvantyagi/zexe/", package = "groth16" }
r1cs_core = {git = "https://github.com/nirvantyagi/zexe/", package = "r1cs-core" }
r1cs_std = {git = "https://github.com/nirvantyagi/zexe/", package = "r1cs-std", features = [ "ed_on_bls12_381" ] }
dh_commitments = {git = "https://github.com/nirvantyagi/ripp/", package = "dh_commitments", branch = "forked_zexe_dependency" }
inner_products = {git = "https://github.com/nirvantyagi/ripp/", package = "inner_products", branch = "forked_zexe_dependency" }
ip_proofs = {git = "https://github.com/nirvantyagi/ripp/", package = "ip_proofs", branch = "forked_zexe_dependency" }
rand = { version = "0.7" }
digest = { version = "0.9" }
num-traits = { version = "0.2" }

crypto_primitives = { path = "../crypto_primitives" }
single_step_avd = { path = "../single_step_avd" }
